In [91]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import tensorflow as tf
from collections import Counter

%matplotlib inline

In [115]:
X = np.load('../Data/white/X.npy')
#Y1 = np.load('../hispanic_colrect/Y1.npy')
Y2 = np.load('../Data/white/Y2.npy')
#Y5 = np.load('../hispanic_colrect/Y5.npy')
X_h = np.load('../Data/hispanic/X.npy')
Y_h = np.load('../Data/hispanic/Y2.npy')

In [130]:
X.shape

(275547, 367)

In [116]:
# shuffle
np.random.seed(42)
idx = np.random.permutation(len(X))
X = X[idx]
Y = Y2[idx]

TEST_SET_SIZE = int(0.1*len(Y))

X_train, X_test = X[:-TEST_SET_SIZE], X[-TEST_SET_SIZE:]
Y_train, Y_test = Y[:-TEST_SET_SIZE].astype(int), Y[-TEST_SET_SIZE:].astype(int)

In [29]:
np.mean(X[:,-4])

63.420465735196274

In [28]:
X[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [117]:
# Features Scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std_scaler = StandardScaler()
X_train[:,-4:] = std_scaler.fit_transform(X_train[:,-4:])
X_test[:,-4:] = std_scaler.transform(X_test[:,-4:])

/Users/sam/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [31]:
X[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [118]:
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.metrics import confusion_matrix

def results(classifier,threshold=0.5, X_test=X_test, Y_test=Y_test):
    Y_pred_test = classifier.predict(X_test)
    Y_pred_test = (Y_pred_test>=threshold).astype(int)
    #Y_pred_test = np.rint(Y_pred_test)
    print("Test accuracy score: " + str(accuracy_score(Y_test.astype(int), Y_pred_test)))
    print("ROC: " + str(roc_auc_score(Y_test.astype(int), Y_pred_test)))
    matrix = confusion_matrix(Y_test.astype(int), Y_pred_test)
    tn, fp, fn, tp = matrix.ravel()
    ppv = tp/(tp+fp)
    npv = tn/(tn+fn)
    sensitivity = tp/(tp+fn)
    specificity = tn/(tn+fp)
    g_mean = np.sqrt(sensitivity*specificity)
    print("PPV: " + str(ppv))
    print("NPV: " + str(npv))
    print("Sensitivity: " + str(sensitivity))
    print("Specificity: " + str(specificity))
    print("G-Mean: " + str(g_mean))
    print("Confusion matrix:\n" + str(matrix))

In [33]:
X_train[0,-4:]

array([0.5208621819106358, -0.4568459141566121, -0.4743095168316912,
       0.19118071958850957], dtype=object)

In [119]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout, BatchNormalization
from keras.models import Sequential

model = Sequential()
#model.add(Dropout(0.25, input_shape=(X.shape[1],)))
model.add(Dense(400, input_dim=X.shape[1], activation=keras.layers.LeakyReLU(alpha=0.1)))
model.add(Dropout(0.25))

model.add(Dense(400, activation=keras.layers.LeakyReLU(alpha=0.1)))
model.add(Dropout(0.25))

model.add(Dense(400, activation=keras.layers.LeakyReLU(alpha=0.1)))
model.add(Dropout(0.25))


model.add(Dense(1, activation='tanh'))

In [120]:
#with tf.Session(graph=graph) as sess:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=3, batch_size=500)
scores = model.evaluate(X_test, Y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/3
247993/247993 [==============================] - 41s 164us/step - loss: 0.3548 - acc: 0.8485
Epoch 2/3
247993/247993 [==============================] - 36s 147us/step - loss: 0.3309 - acc: 0.8555
Epoch 3/3
27554/27554 [==============================] - 7s 257us/step

acc: 85.57%


In [129]:
results(model, threshold=0.75)

Test accuracy score: 0.806815707338
ROC: 0.803675974429
PPV: 0.943370455978
NPV: 0.501643578305
Sensitivity: 0.808809620322
Specificity: 0.798542328537
G-Mean: 0.803659578151
Confusion matrix:
[[ 4273  1078]
 [ 4245 17958]]


In [131]:
results(model, threshold=0.75, X_test=X_h, Y_test=Y_h)

ValueError: Error when checking : expected dense_21_input to have shape (367,) but got array with shape (303,)

In [125]:
Y_pred_test = model.predict(X_test)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [147]:
Y_pred_test[210:230]

array([[ 0.9780362 ],
       [ 0.9742021 ],
       [-0.05996058],
       [ 0.9298522 ],
       [ 0.97326124],
       [ 0.946064  ],
       [ 0.962197  ],
       [ 0.94709915],
       [ 0.9627532 ],
       [ 0.9947199 ],
       [ 0.7142358 ],
       [ 0.96079725],
       [ 0.9714728 ],
       [ 0.9769498 ],
       [ 0.8292747 ],
       [ 0.7820896 ],
       [ 0.48054105],
       [ 0.91638213],
       [ 0.9718184 ],
       [ 0.824868  ]], dtype=float32)

In [148]:
Y_test[210:230]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1])

In [12]:
#with graph.as_default():
Y_pred_test = model.predict(X_test)
Y_pred_test = np.rint(Y_pred_test)

In [13]:
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.metrics import confusion_matrix
#Y_pred_test = grid_search.predict(std_scaler.transform(X_test))
print(accuracy_score(Y_test.astype(int), Y_pred_test))
print("ROC: " + str(roc_auc_score(Y_test.astype(int), Y_pred_test)))
confusion_matrix(Y_test.astype(int), Y_pred_test)

0.823833333333
ROC: 0.738294587901


array([[ 825,  612],
       [ 445, 4118]])

In [130]:
tn, fp, fn, tp = confusion_matrix(Y_test.astype(int), Y_pred_test).ravel()
ppv = tp/(tp+fp)
npv = tn/(tn+fn)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print("PPV: " + str(ppv))
print("NPV: " + str(npv))
print("Sensitivity: " + str(sensitivity))
print("Specificity: " + str(specificity))

PPV: 0.873648505406
NPV: 0.655494933749
Sensitivity: 0.903133903134
Specificity: 0.58524704245
